version: '3.2'
volumes:
  node_modules:
services:
  nodemon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
      - "8050:8050"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - API_HOST=api.agg.loc
      - API_PORT=8000
      - WEB_HOST=app.agg.loc
    command: bash -c "npm run watch"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - redis
    extra_hosts:
      - "api.agg.loc:172.17.0.1"
      - "app.agg.loc:172.17.0.1"

  redis:
    image: redis:3.2.4
    command: redis-server --appendonly yes
