const currentCartItemsResponse = {
  count: 8,
  next: null as string,
  previous: null as string,
  results: [
    {
      id: 58,
      item: '1925cba433ad44299fdb',
      uid: '1925cba433ad44299fdb',
      modified: '2017-10-18T17:25:05.081977Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 19, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: `Childhood's End. Kindle ru`, type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Arthur C. Clarke', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'Kindle version of Ch', type: 'text' },
      },
    },
    {
      id: 57,
      item: '81a0709e8a9c4869b875',
      uid: '81a0709e8a9c4869b875',
      modified: '2017-10-18T17:25:03.613752Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 20, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: `Childhood's End. ePub ru`, type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Arthur C. Clarke', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'ePub version of Chil', type: 'text' },
      },
    },
    {
      id: 56,
      item: '6b8aeac1361142a68501',
      uid: '6b8aeac1361142a68501',
      modified: '2017-10-18T17:24:38.832642Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 13, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: `Childhood's End. PDF ru`, type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Arthur C. Clarke', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'PDF version of Child', type: 'text' },
      },
    },
    {
      id: 55,
      item: 'e33c200d11aa4286a88d',
      uid: 'e33c200d11aa4286a88d',
      modified: '2017-10-18T17:24:38.829789Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 29, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: 'Starship Troopers. Kindle ru', type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Robert A. Heinlein', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'Kindle version of St', type: 'text' },
      },
    },
    {
      id: 54,
      item: '1b763bd00da14acca1a0',
      uid: '1b763bd00da14acca1a0',
      modified: '2017-10-18T17:16:48.752466Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 5, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: 'Starship Troopers. ePub ru', type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Robert A. Heinlein', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'ePub version of Star', type: 'text' },
      },
    },
    {
      id: 53,
      item: 'ecf5a105fcd84d2e8661',
      uid: 'ecf5a105fcd84d2e8661',
      modified: '2017-10-18T17:24:50.016386Z',
      count: 2,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 0, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: 'Starship Troopers. PDF. Free!', type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Robert A. Heinlein', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'PDF version of Stars', type: 'text' },
      },
    },
    {
      id: 52,
      item: '4bfbc17d3e6b4457ba3a',
      uid: '4bfbc17d3e6b4457ba3a',
      modified: '2017-10-18T17:16:48.746593Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 25, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: 'Starship Troopers. PDF ru', type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Robert A. Heinlein', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'PDF version of Stars', type: 'text' },
      },
    },
    {
      id: 51,
      item: '1f5f0f0351144d03be7a',
      uid: '1f5f0f0351144d03be7a',
      modified: '2017-10-13T14:07:00.935238Z',
      count: 1,
      in_stock: true,
      is_deleted: false,
      schema_fields: {
        price: { label: 'Цена', value: 0, type: 'decimal' },
        picture_url: { label: 'Картинка', value: '', type: 'string' },
        name: { label: 'Имя', value: 'Wool. PDF. Free!', type: 'string' },
        currency: { label: 'Валюта', value: '€', type: 'string' },
        author: { type: 'string', in_list: true, value: 'Hugh Howey', label: 'Author' },
        short_description: { label: 'Краткое описание', value: 'PDF version of Wool', type: 'text' },
      },
    },
  ],
};

export default currentCartItemsResponse;
